# Generated by Django 5.2 on 2025-04-05 08:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'AvailableAction',
            },
        ),
        migrations.CreateModel(
            name='AvailableTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'AvailableTrigger',
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggerId', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Flow',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('sortingOrder', models.IntegerField(default=0)),
                ('actionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='database.availableaction')),
                ('flowId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='database.flow')),
            ],
            options={
                'db_table': 'Action',
            },
        ),
        migrations.CreateModel(
            name='FlowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('flowId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowRuns', to='database.flow')),
            ],
            options={
                'db_table': 'FlowRun',
            },
        ),
        migrations.CreateModel(
            name='FlowRunOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flowRunId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flowRunOutbox', to='database.flowrun')),
            ],
            options={
                'db_table': 'FlowRunOutbox',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('flowId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='database.flow')),
                ('triggerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='database.availabletrigger')),
            ],
            options={
                'db_table': 'Trigger',
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='database.user'),
        ),
    ]
