# Generated by Django 5.2 on 2025-04-07 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flow',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flow',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
