# Generated by Django 5.2 on 2025-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_flow_active_flow_createdat_flow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
