# Generated by Django 5.2 on 2025-04-08 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_flow_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowrun',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ActionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('result', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='database.action')),
                ('flowRunId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actionExecutions', to='database.flowrun')),
            ],
            options={
                'db_table': 'ActionExecution',
            },
        ),
    ]
