# Generated by Django 5.2 on 2025-04-05 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('imageUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggerId', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='webhook.user')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('sortingOrder', models.IntegerField(default=0)),
                ('actionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='webhook.availableaction')),
                ('flowId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='webhook.flow')),
            ],
        ),
        migrations.CreateModel(
            name='FlowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('flowId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowRuns', to='webhook.flow')),
            ],
        ),
        migrations.CreateModel(
            name='FlowRunOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flowRunId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flowRunOutbox', to='webhook.flowrun')),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata', models.JSONField(default=dict)),
                ('flowId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='webhook.flow')),
                ('triggerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='webhook.availabletrigger')),
            ],
        ),
    ]
