# Generated by Django 5.2 on 2025-04-05 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0002_availableaction_availabletrigger_flow_action_flowrun_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availabletrigger',
            old_name='imageUrl',
            new_name='image',
        ),
    ]
